[package]
name = "ionia"
version = "1.0.0"
authors = []

[addresses]
starknet_addr = "_"
lib_addr = "_"

[dev-addresses]
starknet_addr = "0xb50b1b8157ebf7315813c1f745a1e1c68c73111afe2b6761975223d317569b69"
lib_addr = "54ba5979fbdf5fa56c4f4b5147fa33068148d08f6f191c23bca865c21192dcaa"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/sota-zk-labs/navori", rev = "layout6", subdir = "libs" }
