[package]
name = "ionia"
version = "1.0.0"
authors = []

[addresses]
starknet_addr = "0xb50b1b8157ebf7315813c1f745a1e1c68c73111afe2b6761975223d317569b69"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.17"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
